name: writernote
adopt-info: writernote
#version: 2.0.6h

summary: Writernote

description: |
  writernote is a multiplatform application that allows you to take notes by recording audio, 
  translate it later into text, and listen to it in an intelligent way.

confinement: strict
grade: stable
base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  writernote:
    #command-chain: ["snap/command-chain/alsa-launch"]
    command: bin/desktop-launch $SNAP/bin/writernote
    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf
      PULSA_CONFIG_PATH: $SNAP/etc/pulse/client.conf.d/01-enable-autospawn.conf
      DISABLE_WAYLAND: 1
      GTK_USE_PORTAL: 1
    
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-record
      - home
      - browser-support
      - network
      - gsettings
      - network-bind
      - audio-playback
      - network-manager

      - cups-control
      - removable-media

    slots:
      - mpris

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

  /usr/share/X11:
    bind: $SNAP/usr/share/X11

  /etc/writernote:
    bind: $SNAP_DATA/etc/writernote

  /etc/pulse:
    bind: $SNAP/etc/pulse

  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

  qt:
    plugin: nil
    build-packages:
      - libdbus-1-dev
      - libegl-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libglib2.0-dev
      - libglx-dev
      - libgtk-3-dev
      - libharfbuzz-dev
      - libice-dev
      - libicu-dev
      - libopengl-dev
      - libpcre2-dev
      - libpng-dev
      - libsm-dev
      - libssl-dev
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxcursor-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - zlib1g-dev
    stage-packages:
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libglib2.0-0
      - libglx0
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu66
      - libopengl0
      - libpcre2-16-0
      - libpng16-16
      - libsm6
      - libssl1.1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
    override-pull: |
      QT=6_3_0
      git clone -b v6.3.0 --depth=1 git://code.qt.io/qt/qt5.git .
      perl init-repository --module-subset=qtbase,qtwayland,qtimageformats,qtsvg,qt5compat,qtmultimedia,qtshadertools
    
    override-build: |
      ./configure \
        -prefix /usr \
        -libdir /usr/lib/$SNAPCRAFT_ARCH_TRIPLET \
        -release \
        -opensource \
        -confirm-license \
        -no-feature-getentropy \
        -no-feature-renameat2 \
        -no-feature-statx \
        -no-feature-egl-extension-platform-wayland \
        -no-feature-highdpiscaling \
        -nomake tools \
        -nomake examples \
        -nomake tests \
        -skip qtwebengine

      cmake --build . -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      DESTDIR="$SNAPCRAFT_PART_INSTALL" cmake --install .
    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    prime:
      - -./usr/bin
      - -./usr/doc
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/metatypes
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.so
      - -./usr/libexec
      - -./usr/mkspecs
      - -./usr/modules
    after:
      - mozjpeg

  mozjpeg:
    source: https://github.com/mozilla/mozjpeg.git
    source-depth: 1
    source-tag: v4.0.3
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_STATIC=OFF
      - -DWITH_JPEG8=ON
      - -DPNG_SUPPORTED=OFF
    prime:
      - -./usr/bin
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.so
      - -./usr/share

  poppler:
    after: [qt]
    plugin: make
    build-packages:
      - libnss3-dev
      - libboost-dev
      - libopenjp2-7-dev
      - wget
    stage-packages:
      - libnss3
      - libopenjp2-7
    override-pull: |
      #wget https://poppler.freedesktop.org/poppler-22.01.0.tar.xz
      #tar -xf poppler-22.01.0.tar.xz

    override-build: |
      cd 3rdparty/poppler
      mkdir build; cd build

      cmake .. -DCMAKE_FIND_DEBUG_MODE=1

      make -j$(nproc)
      make install

      mkdir -p $SNAPCRAFT_PRIME/usr/
      mkdir -p $SNAPCRAFT_PRIME/usr/lib
      mkdir -p $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET 

      cp /usr/local/lib/libpoppler* $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/
      cd $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/
      
    prime:
      - -./usr/include/poppler
      - -./usr/include/poppler/qt6
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.so
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpoppler*
      - -./usr/bin
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/local/lib/*.so
      - -./usr/share
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpoppler-qt6.so.3
    stage:
      - -./usr/local/$SNAPCRAFT_ARCH_TRIPLET/libpoppler*
      - -./usr/include/poppler

  writernote:
    after: [desktop-qt5, alsa-mixin, qt, poppler]
    
    plugin: make
    source: .
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    override-build: |
      set -eux

      export PATH=$PATH:/root/parts/qt/install/usr/bin/
      
      export VERSION=$(git describe --tags --abbrev=0)

      snapcraftctl set-version "$VERSION"
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      ls $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/

      cmake . \
        -DVERSION_SNAPCRAFT=$VERSION \
        -DSNAP=ON \
        -DPOPPLER_INCLUDE_DIR=/usr/local/include/poppler/qt6 \
        -DPOPPLER_LIB_1=/root/prime/usr/lib/x86_64-linux-gnu/libpoppler-qt6.so.3 \
        -DPOPPLER_LIB_2=/root/prime/usr/lib/x86_64-linux-gnu/libpoppler.so.117  \
        -DCMAKE_FIND_DEBUG_MODE=1 \
        -DCMAKE_BUILD_TYPE=Release \
        -DQt6_DIR=/root/parts/qt/install/usr/lib/x86_64-linux-gnu/cmake/Qt6/

      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      
      cp writernote $SNAPCRAFT_PART_INSTALL/bin/
      cd $SNAPCRAFT_PART_INSTALL/bin
      ldd writernote


    build-packages:
      - libzip-dev
      - libxcb-xinerama0-dev
      - libx11-xcb-dev 
      - libwayland-dev
      - libglu1-mesa-dev 
      - libxrender-dev 
      - libxi-dev 
      - libxkbcommon-dev 
      - libxkbcommon-x11-dev
      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev 
      - libgstreamer-plugins-good1.0-dev 
      - libgstreamer-plugins-bad1.0-dev
      - execstack
      - libasound2-dev
      - libopus-dev
      - libglib2.0-dev
      - liblzma-dev
      - libssl-dev
      - libxcb1-dev
      - libxcb-screensaver0-dev
      - zlib1g-dev
      - libglibmm-2.4-dev
    stage-packages:
      - libglu1-mesa
      - libnss3 
      - libzip5
      - libglibmm-2.4-1v5
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libglib2.0-0
      - libglx0
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu66
      - libopengl0
      - libpcre2-16-0
      - libpng16-16
      - libsm6
      - libssl1.1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
      - gstreamer1.0-plugins-base 
      - gstreamer1.0-plugins-good 
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-libav 
      - gstreamer1.0-tools 
      - gstreamer1.0-x 
      - gstreamer1.0-alsa 
      - gstreamer1.0-gl 
      - gstreamer1.0-gtk3
      - gstreamer1.0-pulseaudio

    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs
    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    after:
      - mozjpeg
      - qt
