name: writernote
version: 2.0.6h

summary: Writernote

description: |
  writernote is a multiplatform application that allows you to take notes by recording audio, 
  translate it later into text, and listen to it in an intelligent way.

confinement: strict

base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  writernote:
    #command-chain: ["snap/command-chain/alsa-launch"]
    command: bin/desktop-launch $SNAP/bin/writernote
    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf
      PULSA_CONFIG_PATH: $SNAP/etc/pulse/client.conf.d/01-enable-autospawn.conf
      DISABLE_WAYLAND: 1

    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-record
      - home
      - browser-support
      - network
      - gsettings
      - network-bind
      - audio-playback
      - network-manager

      - cups-control
      - removable-media

    slots:
      - mpris


layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

  /usr/share/X11:
    bind: $SNAP/usr/share/X11

  /etc/writernote:
    bind: $SNAP_DATA/etc/writernote

  /etc/pulse:
    bind: $SNAP/etc/pulse


plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

  qt:
    plugin: nil
    build-packages:
      - libdbus-1-dev
      - libegl-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libgl-dev
      - libglib2.0-dev
      - libharfbuzz-dev
      - libicu-dev
      - libpcre2-dev
      - libpng-dev
      - libssl-dev
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-xinput-dev
      - libxcb-xkb-dev
      - libxcursor-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - zlib1g-dev
    stage-packages:
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libgl1
      - libglib2.0-0
      - libharfbuzz0b
      - libicu66
      - libpcre2-16-0
      - libpng16-16
      - libssl1.1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
    override-pull: |
      QT=5_15_2
      git clone git://code.qt.io/qt/qt5.git .

      perl init-repository --module-subset=qtbase,qtimageformats,qtmultimedia

      git checkout v5.15.2

      git submodule update qtbase
      git submodule update qtimageformats 
      git submodule update qtmultimedia     
    
    override-build: |
      ./configure \
        -prefix /src \
        -static-runtime \
        -release \
        -opensource \
        -confirm-license \
        -qt-zlib \
        -qt-pcre \
        -qt-libpng \
        -qt-libjpeg \
        -qt-freetype \
        -opengl desktop \
        -sql-sqlite \
        -make libs \
        -nomake tools \
        -nomake examples \
        -nomake tests \
        -skip qtwebengine

      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      sudo make install
    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    prime:
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/bin
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/mkspecs
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/examples
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.so
      - -./usr/lib/qt5
      - -./usr/share
    after:
      - mozjpeg

  mozjpeg:
    source: https://github.com/mozilla/mozjpeg.git
    source-depth: 1
    source-tag: v4.0.3
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_STATIC=OFF
      - -DWITH_JPEG8=ON
      - -DPNG_SUPPORTED=OFF
    prime:
      - -./usr/bin
      - -./usr/include
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*.so
      - -./usr/share

  poppler:
    after: [qt]
    plugin: make
    build-packages:
      - libnss3-dev
      - libboost-dev
      - libopenjp2-7-dev
    stage-packages:
      - libnss3
      - libopenjp2-7

    override-build: |
      wget https://poppler.freedesktop.org/poppler-22.01.0.tar.xz
      tar -xf poppler-22.01.0.tar.xz
      cd poppler-22.01.0
      mkdir build
      cd build
      cmake .. \
        -DQt5Core_DIR=/src/lib/cmake/Qt5Core \
        -DQt5Xml_DIR=/src/lib/cmake/Qt5Xml \
        -DQt5Gui_DIR=/src/lib/cmake/Qt5Gui \
        -DQt5Widgets_DIR=/src/lib/cmake/Qt5Widgets \
        -DQt5Test_DIR=/src/lib/cmake/Qt5Test

      make -j$(nproc)
      sudo make install

  writernote:
    after: [desktop-qt5, alsa-mixin, qt, poppler]
    
    plugin: make
    source: .

    override-build: |
      set -eux
      export PATH=$PATH:/src/bin/

      qmake -set prefix $SNAPCRAFT_PART_INSTALL

      #printf "%s\n" "$(SNAPCRAFT_PROJECT_VERSION)"
      #make clean

      qmake DEFINES+="SNAP" DEFINES+=VERSION_SNAPCRAFT=$SNAPCRAFT_PROJECT_VERSION DEFINES+=QT_NO_DEBUG_OUTPUT INCLUDE_PATH+="/usr/local/include/poppler/qt5"

      snapcraftctl build
      [ ! -d "$SNAPCRAFT_PART_INSTALL/bin" ] && mkdir $SNAPCRAFT_PART_INSTALL/bin/
      ldd build/writernote
      cp build/writernote $SNAPCRAFT_PART_INSTALL/bin/


    build-packages:
      - libzip-dev
      - libxcb-xinerama0-dev
      - libx11-xcb-dev 
      - libglu1-mesa-dev 
      - libxrender-dev 
      - libxi-dev 
      - libxkbcommon-dev 
      - libxkbcommon-x11-dev
      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev 
      - libgstreamer-plugins-good1.0-dev 
      - libgstreamer-plugins-bad1.0-dev
      - execstack
      - libasound2-dev
      - libopus-dev
      - libglib2.0-dev
      - liblzma-dev
      - libssl-dev
      - libxcb1-dev
      - libxcb-screensaver0-dev
      - zlib1g-dev
      - libglibmm-2.4-dev
    stage-packages:
      - libzip5
      - libglibmm-2.4-1v5
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libglib2.0-0
      - libglx0
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu66
      - libopengl0
      - libpcre2-16-0
      - libpng16-16
      - libsm6
      - libssl1.1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
      - gstreamer1.0-plugins-base 
      - gstreamer1.0-plugins-good 
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-libav 
      - gstreamer1.0-tools 
      - gstreamer1.0-x 
      - gstreamer1.0-alsa 
      - gstreamer1.0-gl 
      - gstreamer1.0-gtk3
      - gstreamer1.0-pulseaudio

    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
  
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs
    stage:
      - -./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    after:
      - mozjpeg
      - qt
