name: Linux build qt6

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'updater/**'
      - 'windows/**'
      - 'macos-build/**'
      - '!.github/workflows/linux qt6.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'macos-build/**'
      - '!.github/workflows/linux qt6.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run a one-line script
        run: |
          sudo apt update
          sudo apt -y install libzip-dev
          sudo apt -y install libfreetype-dev libfontconfig1-dev 
          sudo apt -y install libtiff-dev libnss3-dev libcairo2-dev
          sudo apt -y install libboost-all-dev libopenjp2-7-dev
          sudo snap install cmake --classic

      - name: Install Qt6
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 6.2.0
          modules: multimedia

      - name: Build poppler
        run: |
          #wget https://github.com/freedesktop/poppler/archive/refs/tags/poppler-21.10.0.zip
          #unzip poppler-21.10.0.zip
          #rm poppler-21.10.0.zip
          #cd poppler-poppler-21.10.0

          echo $(pwd)
          cd 3rdparty/poppler

          mkdir install
          
          cmake . \
            -DCMAKE_INSTALL_LIBDIR=$(pwd)/install/ \
            -DCMAKE_INSTALL_INCLUDEDIR=$(pwd)/install/
          make -j$(nproc)
          sudo make install

      - name: CMake compile
        run: |
          sudo find / -name "Qt6MultimediaConfig.cmake"
          cmake .
          make -j$(nproc)
