name: Linux build qt6

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'updater/**'
      - 'windows/**'
      - 'macos-build/**'
      - '!.github/workflows/linux qt6.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'macos-build/**'
      - '!.github/workflows/linux.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          sudo apt update
          sudo apt -y install libzip-dev
          sudo apt -y install libfreetype-dev libfontconfig1-dev 
          sudo apt -y install libtiff-dev libnss3-dev libcairo2-dev
          sudo apt -y install libboost-all-dev libopenjp2-7-dev
          sudo apt install libpoppler-qt5-dev
          sudo snap install cmake --classic

      - name: Install Qt5
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 5.15.2
          modules: multimedia

      - name: Build poppler
        if: false
        run: |
          wget https://github.com/freedesktop/poppler/archive/refs/tags/poppler-21.10.0.zip
          unzip poppler-21.10.0.zip
          rm poppler-21.10.0.zip
          cd poppler-poppler-21.10.0

          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install
      
      - name: Compile NO_ALL_VERSION (release)
        run: |
          echo $(ls /usr/local/include/poppler/qt5)
          qmake DEFINES+="NO_ALL_VERSION"
          make -j $(nproc)    

      - name: Compile ALL_VERSION (release)
        run: |
          make clean
          qmake
          make -j $(nproc)

      - name: Compile (debug)
        run: |
          make clean
          qmake CONFIG+=debug
          make -j $(nproc)

      - name: Install Qt6
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 6.3.0
          modules: multimedia

      - name: CMake compile
        run: |
          make clean
          rm -r build
          mkdir build; cd build
          cmake ..
          make -j $(nproc)
