name: Linux build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'updater/**'
      - 'windows/**'
      - 'macos-build/**'
      - '!.github/workflows/linux.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'macos-build/**'
      - '!.github/workflows/linux.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          sudo apt install libpoppler-qt5-dev
          sudo apt -y install libzip-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 5.15.2 # optional, default is 5.15.2
          modules: multimedia # optional
          
      - name: Compile ALL_VERSION
        run: |
          qmake
          make -j $(nproc)
          
      - name: Compile NO_ALL_VERSION
        run: |
          make clean
          qmake DEFINES+="NO_ALL_VERSION"
          make -j $(nproc)
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go, javascript

      # Here is where you build your code
      - run: |
          make bootstrap
          make release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1