name: Linux build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'updater/**'
      - 'windows/**'
      - 'macos-build/**'
      - '!.github/workflows/linux.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'macos-build/**'
      - '!.github/workflows/linux.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          #sudo apt install libpoppler-qt5-dev
          sudo apt -y install libzip-dev
          sudo apt -y install libfreetype-dev libfontconfig1-dev libtiff-dev libnss3-dev libcairo2-dev libboost-all-dev libopenjp2-7-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 5.15.2 # optional, default is 5.15.2
          modules: multimedia # optional

      - name: Build poppler
        run: |
          wget https://github.com/freedesktop/poppler/archive/refs/tags/poppler-21.10.0.zip
          unzip poppler-21.10.0.zip
          rm poppler-21.10.0.zip
          cd poppler-poppler-21.10.0

          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          
      - name: Compile NO_ALL_VERSION
        run: |
          echo $(ls /usr/local/include/poppler/qt5)
          qmake DEFINES+="NO_ALL_VERSION" INCLUDEPATH+=/usr/local/include/poppler/qt5 LIBS+=/usr/local/lib/libpoppler-qt5.so.1
          make -j $(nproc)    

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1