name: macos build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'updater/**'
      - 'windows/**'
      - '!.github/workflows/macos.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/macos.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      QT: "5_15_2"
      QT_PREFIX: "/usr/local/desktop-app/Qt-5.15.2"
      PREFIX: "/usr/local/macos"

    steps:
      - uses: actions/checkout@v2

      - name: First set up
        run: |
          brew install automake libtool libvorbis libvpx \
            ninja opus sdl pkg-config

      #- name: Install Qt
      #  uses: jurplel/install-qt-action@v2.13.2
      #  with:
      #    version: 5.15.2
      #    modules: multimedia

      - name: Qt 5.15.2 cache.
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ env.LibrariesPath }}/qt-cache
          key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}-${{ hashFiles('**/qtbase_5_15_2/*') }}

      - name: Use cached Qt 5.15.2.
        if: steps.cache-qt.outputs.cache-hit == 'true'
        run: |
          cd $LibrariesPath
          mv qt-cache Qt-5.15.2
          sudo mkdir -p $QT_PREFIX
          sudo mv -f Qt-5.15.2 "$(dirname "$QT_PREFIX")"/

      - name: Build Qt 5.15.2
        run: | 
          mkdir build_qt
          git clone git://code.qt.io/qt/qt5.git qt_$QT
          cd qt_$QT
          perl init-repository --module-subset=qtbase,qtimageformats
          git checkout v5.15.2
          git submodule update qtbase
          git submodule update qtimageformats
          cd qtbase
          find ../../patches/qtbase_$QT -type f -print0 | sort -z | xargs -0 git apply
          cd ..
          ./configure \
          -prefix "$QT_PREFIX" \
          -debug \
          -force-debug-info \
          -opensource \
          -confirm-license \
          -static \
          -opengl desktop \
          -no-openssl \
          -securetransport \
          -nomake examples \
          -nomake tests \
          -platform macx-clang \
          -I "$PREFIX/include" \
          LIBJPEG_LIBS="$PREFIX/lib/libjpeg.a" \
          ZLIB_LIBS="$PREFIX/lib/libz.a"
          make -j$(nproc)
          sudo make install
          make clean
          echo $(LibrariesPath)
          cp -r $QT_PREFIX $LibrariesPath/qt-cache

      - name: Build libzip
        run: |
          curl -L https://libzip.org/download/libzip-1.5.2.tar.gz -o libzip.tar.gz
          tar xf libzip.tar.gz
          cd libzip-* || exit
          mkdir build
          cd build || exit
          echo "Build LibZip"
          pwd
          cd build
          cmake ..
          cd ..
          make -j8
          make install

      - name: Download dep
        run: |
          ./macos-build/dep.sh

      - name: Compile
        run: |
          ./macos-build/compile.sh
          
