name: Snap

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/snapcraft.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/snapcraft.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo apt -y install libzip-dev

      - name: First set up.
        run: |
          sudo apt-get purge --autoremove lxd
          sudo snap install --classic snapcraft
          sudo snap install lxd
          
          sudo chown root:root /
          sudo usermod -aG lxd $USER
          sudo snap run lxd init --auto
          sudo snap run lxd waitready
          
      - name: writernote snap build.
        run: sg lxd -c 'snap run snapcraft --use-lxd'
