name: snap linux
 
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          sudo apt -y install snapd
          sudo snap install snapcraft --classic
          sudo snap install multipass
          
          snapcraft
