name: Windows

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/windows.yml'
      - 'macos-build/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/windows.yml'
      - 'macos-build/**'

  release:
    types:
      - published

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone.
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}
                  
      - uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 6e4fbee0d1e6daffaab50f4c055cd3ccfd3d929a }

      - name: Install lib
        run: |
          vcpkg install qt:x64-windows