name: Windows package

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2


      - name: Download dependency
        if: ${{ github.event_name == 'release' }} # skip for testing
        run: |
          set PATH="%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc ./windows/dipendenze.sh #$(pwd)"/windows/dipendenze.sh"
        shell: cmd
        working-directory: windows
        env:
          HOME: ${{ runner.workspace }}/writernote-qt
          MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64
          
      - name: Build
        if: ${{ github.event_name == 'release' }} # skip for testing
        run: |
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc "./windows/compile.sh"
        shell: cmd
        working-directory: windows
        env:
          HOME: ${{ runner.workspace }}/writernote-qt
          MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64

      - name: download innoextract, innosetup
        shell: powershell
        run: |
          $destination_folder = "D:/a/writernote-qt"
          
          cd $destination_folder

          Invoke-WebRequest -Uri "https://constexpr.org/innoextract/files/innoextract-1.9-windows.zip" -OutFile "innoextract-1.9-windows.zip"
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"

      - name: Extract innoextract and is.exe
        shell: powershell
        run: |
          $destination_folder = "D:/a/writernote-qt"
          cd $destination_folder

          Expand-Archive -Force -Path innoextract-1.9-windows.zip -DestinationPath $destination_folder           
          .\innoextract.exe "$destination_folder\is.exe"

      - name: Move to program
        shell: powershell
        run: |
          $dest_win = "C:\Program Files (x86)\Inno Setup 6\"
          $dest = "D:\a\writernote-qt\"
          mv $dest\app $dest_win

      - name: Compile package for windows
        #if: ${{ github.event_name == 'release' }}
        shell: powershell
        run: |
          $curr_dir = "D:/a/writernote-qt/"
          cd $curr_dir
          
          start windows/compile.bat
          
