# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install MinGW
        # You may pin to the exact commit or the version.
        # uses: egor-tensin/setup-mingw@f3c5d799aadf8fa230ac67a422b01dd085bbc96b
        uses: egor-tensin/setup-mingw@v2
        #with:
          # Target platform
          #platform: # optional, default is x64
          # Install Cygwin packages
          #cygwin: # optional, default is 0
          # Enable static linking workaround
          #static: # optional, default is 1
          # Set up cc/c++ executables
          #cc: # optional, default is 1
          # On Cygwin, replace executable symlinks with hardlinks
          #hardlinks: # optional, default is 0


      - name: Download dependency
        run: |
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc "./windows/dipendenze.sh"
      
      - name: Build
        run: | 
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc "./windows/compile.sh"

      - name: Create package for windows
        run: |
          echo ""
  
