name: Windows package

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2


      - name: Download dependency
        run: |
          set PATH="%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc $(pwd)"/windows/dipendenze.sh"
        shell: cmd
        working-directory: windows
      
      - name: Build
        run: |
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc "./compile.sh"
        shell: cmd
        working-directory: windows


      - name: Create package for windows
        run: |
          echo ""
        
