name: Windows package

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2


      - name: Download dependency
        run: |
          set PATH="%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc ./windows/dipendenze.sh #$(pwd)"/windows/dipendenze.sh"
        shell: cmd
        working-directory: windows
        env:
          HOME: ${{ runner.workspace }}/writernote-qt
          MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64
          
      - name: Build
        run: |
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc "./windows/compile.sh"
        shell: cmd
        working-directory: windows
        env:
          HOME: ${{ runner.workspace }}/writernote-qt
          MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64

      - name: Create package for windows
        #if: ${{ github.event_name == 'release' }}
        run: |
          set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin"
          C:\msys64\usr\bin\bash -lc "wget https://constexpr.org/innoextract/files/innoextract-1.9-windows.zip --directory-prefix=$GITHUB_WORKSPACE"
          C:\msys64\usr\bin\bash -lc "wget https://jrsoftware.org/download.php/is.exe --directory-prefix=$GITHUB_WORKSPACE"

          tar -xf $(GITHUB_WORKSPACE)\innoextract-1.9-windows.zip

          $(GITHUB_WORKSPACE)\innoextract.exe is.exe

          mv $(GITHUB_WORKSPACE)/app "C:\Program Files (x86)\Inno Setup 6\"

          start $(GITHUB_WORKSPACE)/windows/compile.bat
          
          echo "Packaging successful"

        shell: cmd
        working-directory: windows
        env:
          GITHUB_WORKSPACE: GITHUB_WORKSPACE
          HOME: ${{ runner.workspace }}/writernote-qt
          MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64
